# Generated by Django 5.2.4 on 2025-07-10 20:16

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='claim',
            name='claims_clai_company_811fdc_idx',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='accounting_period',
        ),
        migrations.AddField(
            model_name='claim',
            name='accounting_period_end',
            field=models.DateField(default=datetime.date(2025, 3, 31), help_text='End date of accounting period'),
        ),
        migrations.AddField(
            model_name='claim',
            name='accounting_period_start',
            field=models.DateField(default=datetime.date(2024, 4, 1), help_text='Start date of accounting period'),
        ),
        migrations.AddField(
            model_name='costlineitem',
            name='cost_date',
            field=models.DateField(blank=True, help_text='Date when the cost was incurred (for period-specific calculations)', null=True),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['company', 'accounting_period_start', 'accounting_period_end'], name='claims_clai_company_e0cd98_idx'),
        ),
    ]
