# Generated by Django 5.0.2 on 2025-07-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_remove_claim_claims_clai_company_811fdc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcategory',
            name='category',
            field=models.CharField(choices=[('staff', 'Staff Costs'), ('subcontractor', 'Subcontractor Costs'), ('epw', 'Externally Provided Workers'), ('software', 'Software Costs'), ('consumables', 'Consumables'), ('other', 'Other Costs')], max_length=20),
        ),
    ]
