# Generated by Django 5.0.2 on 2025-07-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_costcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costlineitem',
            name='tags',
            field=models.JSONField(blank=True, default=dict, help_text='Tags and additional data like individual amounts'),
        ),
    ]
